name: minha primeira linha de montagem

on:
    push:
        branches: [ main ]
        runs-on: ubuntu-latest

        steps:
          - name: 1. pegar chassi do carro (codigo-fonte): 
            uses: actions/chekut@v3

          - name: 2. estação de bild (montagem)
            run: echo "comstruindo o projeto...varificando se todas as peças se encaixão"

          - name: 3. estação de teste (controle de qualidade)
            run: echo "rodando os testes automatizados...verificando se a porta abre e fecha"
           



          
